window.CLF_QUESTIONS = [
  {
    "id": 1,
    "domain": "D1",
    "body": "クラウドの弾力性（Elasticity）の説明として最も適切なものはどれか。",
    "choice_a": "データを永久に削除できないこと",
    "choice_b": "負荷に応じてリソースを自動的に増減できること",
    "choice_c": "最初に最大構成を購入しておくこと",
    "choice_d": "必ず1台の大型サーバで処理すること",
    "correct": "B",
    "explain": "弾力性は今の負荷に合わせて伸縮すること。最初から最大構成を買うのはオンプレの発想。"
  },
  {
    "id": 2,
    "domain": "D1",
    "body": "スケーラビリティの説明として適切なものはどれか。",
    "choice_a": "インターネット接続を禁止すること",
    "choice_b": "料金を固定で前払いすることだけ",
    "choice_c": "システムを必要に応じて拡張できる能力",
    "choice_d": "障害時に必ずデータが消えること",
    "correct": "C",
    "explain": "スケーラビリティは伸ばせる能力。弾力性は実際に増減する動き。"
  },
  {
    "id": 3,
    "domain": "D1",
    "body": "俊敏性（Agility）がクラウドの利点とされる理由はどれか。",
    "choice_a": "ハードウェアの納期が数ヶ月かかる",
    "choice_b": "変更は年1回に限られる",
    "choice_c": "必ずデータセンターへ出張する",
    "choice_d": "数分で新しい環境を用意して試せる",
    "correct": "D",
    "explain": "調達待ちが短いので実験とリリースが速い。"
  },
  {
    "id": 4,
    "domain": "D1",
    "body": "高可用性（High Availability）を実現する基本的な考え方はどれか。",
    "choice_a": "複数のAZに分散して単一障害点を減らす",
    "choice_b": "1つのAZにすべて集約する",
    "choice_c": "バックアップを取らずに運用する",
    "choice_d": "ルートユーザーだけで操作する",
    "correct": "A",
    "explain": "HAは止まらないこと。複数AZが基本。"
  },
  {
    "id": 5,
    "domain": "D1",
    "body": "CapExとOpExの説明として正しいものはどれか。",
    "choice_a": "CapExは従量課金のことである",
    "choice_b": "CapExは初期の大型投資、OpExは使った分の経費",
    "choice_c": "どちらも同じ意味である",
    "choice_d": "OpExはサーバを買う費用だけを指す",
    "correct": "B",
    "explain": "オンプレはCapEx寄り、クラウドはOpEx寄り。"
  },
  {
    "id": 6,
    "domain": "D1",
    "body": "クラウドに移行するとコスト面で起きやすい変化はどれか。",
    "choice_a": "料金は常に無料になる",
    "choice_b": "データ転送は常に無制限無料になる",
    "choice_c": "固定の設備投資から変動費（従量課金）へ移る",
    "choice_d": "必ず総費用が10倍になる",
    "correct": "C",
    "explain": "使った分だけ払うモデルに変わる。総額が必ず下がるわけではない。"
  },
  {
    "id": 7,
    "domain": "D1",
    "body": "Well-Architected Frameworkの柱に含まれないものはどれか。",
    "choice_a": "セキュリティ",
    "choice_b": "信頼性",
    "choice_c": "コスト最適化",
    "choice_d": "マーケティング最適化",
    "correct": "D",
    "explain": "6本柱は運用上の優秀性・セキュリティ・信頼性・パフォーマンス効率・コスト最適化・持続可能性。"
  },
  {
    "id": 8,
    "domain": "D1",
    "body": "Well-Architectedの「信頼性」の柱で重視することはどれか。",
    "choice_a": "障害から回復し、需要の変化に耐えること",
    "choice_b": "広告のクリック率を上げること",
    "choice_c": "OSの壁紙を統一すること",
    "choice_d": "ルートユーザーを共有すること",
    "correct": "A",
    "explain": "Reliability は故障しても動き続ける設計。"
  },
  {
    "id": 9,
    "domain": "D1",
    "body": "Well-Architectedの「パフォーマンス効率」で行うことはどれか。",
    "choice_a": "暗号化を無効にする",
    "choice_b": "要件に合うコンピューティング資源を選ぶ",
    "choice_c": "すべてのワークロードを最大インスタンスにする",
    "choice_d": "監視をしない",
    "correct": "B",
    "explain": "適切なサイズ・適切なサービスを選ぶ。"
  },
  {
    "id": 10,
    "domain": "D1",
    "body": "Well-Architectedの「持続可能性」の柱が目指すことはどれか。",
    "choice_a": "IAMを廃止する",
    "choice_b": "AZを1つに固定する",
    "choice_c": "環境への影響を減らす",
    "choice_d": "請求書の色を変える",
    "correct": "C",
    "explain": "Sustainability。必要以上のリソースを使わないことも含む。"
  },
  {
    "id": 11,
    "domain": "D1",
    "body": "AWS CAF（Cloud Adoption Framework）の目的として適切なものはどれか。",
    "choice_a": "EC2のOSを自動でインストールするだけ",
    "choice_b": "DNSの名前解決だけを行う",
    "choice_c": "請求書を紙で送る",
    "choice_d": "組織がクラウドへ移行するための観点を整理する",
    "correct": "D",
    "explain": "CAFはビジネス・人材・ガバナンス等の視点で移行を助ける。"
  },
  {
    "id": 12,
    "domain": "D1",
    "body": "クラウドの利点として適切でないものはどれか。",
    "choice_a": "初期費用ゼロで無制限に無料になることが保証される",
    "choice_b": "全球的な展開がしやすい",
    "choice_c": "需要に応じて伸縮できる",
    "choice_d": "従量課金を選べる",
    "correct": "A",
    "explain": "無料が保証されるわけではない。無料利用枠は条件付き。"
  },
  {
    "id": 13,
    "domain": "D1",
    "body": "スケールアウトの説明はどれか。",
    "choice_a": "DNSを停止すること",
    "choice_b": "サーバの台数を増やして処理能力を上げる",
    "choice_c": "1台のCPUを高性能に取り替えるだけ",
    "choice_d": "ディスクを取り外すこと",
    "correct": "B",
    "explain": "水平スケール。垂直はスケールアップ。"
  },
  {
    "id": 14,
    "domain": "D1",
    "body": "スケールアップの説明はどれか。",
    "choice_a": "リージョンを削除する",
    "choice_b": "IAMユーザーを増やすこと",
    "choice_c": "1台のインスタンスをより大きなサイズにする",
    "choice_d": "同じサイズの台数を増やす",
    "correct": "C",
    "explain": "垂直スケール。限界がある。"
  },
  {
    "id": 15,
    "domain": "D1",
    "body": "マネージドサービスを使う主な利点はどれか。",
    "choice_a": "顧客がハードウェアを自前で置く必要がある",
    "choice_b": "必ずオンプレより高い",
    "choice_c": "暗号化ができなくなる",
    "choice_d": "OSパッチなど基盤運用をAWSに任せられる",
    "correct": "D",
    "explain": "RDSやLambdaは運用負荷を下げられる。"
  },
  {
    "id": 16,
    "domain": "D1",
    "body": "オンプレミス環境の特徴として正しいものはどれか。",
    "choice_a": "自社でハードウェアを所有・運用する",
    "choice_b": "必ずAWSが物理サーバを管理する",
    "choice_c": "従量課金以外は選べない",
    "choice_d": "インターネット経由でしか使えない",
    "correct": "A",
    "explain": "オンプレは自社設備。クラウドはプロバイダ設備。"
  },
  {
    "id": 17,
    "domain": "D1",
    "body": "ハイブリッドクラウドの説明として適切なものはどれか。",
    "choice_a": "モバイル回線だけを使う",
    "choice_b": "オンプレミスとクラウドを組み合わせて使う",
    "choice_c": "必ずAWSだけを使う",
    "choice_d": "インターネットを使ってはいけない",
    "correct": "B",
    "explain": "Direct ConnectやVPNでつなぐ構成が典型。"
  },
  {
    "id": 18,
    "domain": "D1",
    "body": "クラウドの規模の経済（economies of scale）が意味することはどれか。",
    "choice_a": "料金が毎日2倍になる",
    "choice_b": "AZを使えなくなる",
    "choice_c": "多数の顧客でインフラを共有し単価を下げられる",
    "choice_d": "1社だけで巨大なデータセンターを必ず持つ",
    "correct": "C",
    "explain": "AWSのような大規模事業者が単価を下げられる。"
  },
  {
    "id": 19,
    "domain": "D1",
    "body": "Rightsizing（適切なサイズ化）の説明はどれか。",
    "choice_a": "常に最大サイズを選ぶ",
    "choice_b": "監視せずに放置する",
    "choice_c": "スポットだけを使うこと",
    "choice_d": "実際の使用量に合わせてインスタンスサイズを見直す",
    "correct": "D",
    "explain": "無駄な過大構成をやめる。コスト最適化。"
  },
  {
    "id": 20,
    "domain": "D1",
    "body": "クラウドで実験（実験的開発）がしやすい理由はどれか。",
    "choice_a": "環境をすぐ作って不要ならすぐ止められる",
    "choice_b": "サーバ購入に数ヶ月かかる",
    "choice_c": "失敗するとハードウェアが廃棄できない",
    "choice_d": "変更は年1回だけ",
    "correct": "A",
    "explain": "失敗のコストが小さい。Agility。"
  },
  {
    "id": 21,
    "domain": "D1",
    "body": "耐障害性（Fault tolerance）に近い説明はどれか。",
    "choice_a": "1つのディスクだけに保存する",
    "choice_b": "一部が壊れてもサービスを継続できる",
    "choice_c": "壊れたら必ず全停止する設計",
    "choice_d": "バックアップを禁止する",
    "correct": "B",
    "explain": "冗長化。HAと近いが「壊れても続く」に焦点。"
  },
  {
    "id": 22,
    "domain": "D1",
    "body": "災害対策（Disaster Recovery）で複数リージョンを使う主な理由はどれか。",
    "choice_a": "料金が必ず無料になるから",
    "choice_b": "IAMが不要になるから",
    "choice_c": "広域災害でも別の地理に復旧できる",
    "choice_d": "同一ラック内の冗長だけで十分だから",
    "correct": "C",
    "explain": "リージョンは地理的に離れている。"
  },
  {
    "id": 23,
    "domain": "D1",
    "body": "従量課金の利点として適切なものはどれか。",
    "choice_a": "24時間最大構成でも料金は同じ",
    "choice_b": "停止しても課金が下がらないことが保証される",
    "choice_c": "データ転送は常に無料",
    "choice_d": "使わない時間はコストを下げやすい",
    "correct": "D",
    "explain": "止める・縮小すると払う量が減る（サービスによる）。"
  },
  {
    "id": 24,
    "domain": "D1",
    "body": "AWSの責任共有モデルが「クラウドの概念」でも問われる理由はどれか。",
    "choice_a": "セキュリティの境界を理解することがクラウド利用の前提だから",
    "choice_b": "顧客が建物の警備をするから",
    "choice_c": "AWSが顧客データをすべて閲覧するから",
    "choice_d": "IAMが禁止されているから",
    "correct": "A",
    "explain": "何をAWSが守り、何を自分が守るかを知る必要がある。"
  },
  {
    "id": 25,
    "domain": "D1",
    "body": "インフラストラクチャをコードで管理する利点はどれか。",
    "choice_a": "本番と開発で構成を揃えられない",
    "choice_b": "同じ構成を繰り返し・版管理できる",
    "choice_c": "毎回コンソールを手作業する方が速いと限られるため不要",
    "choice_d": "変更履歴が残らない",
    "correct": "B",
    "explain": "CloudFormationなどのIaC。"
  },
  {
    "id": 26,
    "domain": "D1",
    "body": "クラウド移行で減りやすいものはどれか。",
    "choice_a": "ネットワークの知識の必要性",
    "choice_b": "IAMの必要性",
    "choice_c": "サーバ購入などの大きな初期投資",
    "choice_d": "セキュリティの必要性そのもの",
    "correct": "C",
    "explain": "設備投資は減りやすい。セキュリティ責任は残る。"
  },
  {
    "id": 27,
    "domain": "D1",
    "body": "「グローバルに展開しやすい」の具体例として適切なものはどれか。",
    "choice_a": "東京だけに固定する",
    "choice_b": "エッジロケーションを使ってはいけない",
    "choice_c": "Route 53を禁止する",
    "choice_d": "ユーザーに近いリージョンに複製して遅延を減らす",
    "correct": "D",
    "explain": "複数リージョンとCloudFrontが典型。"
  },
  {
    "id": 28,
    "domain": "D1",
    "body": "クラウドの設計原則として適切なものはどれか。",
    "choice_a": "失敗を前提に自動復旧できる設計にする",
    "choice_b": "手動オペレーションだけに頼る",
    "choice_c": "監視しない",
    "choice_d": "単一サーバにすべて集約する",
    "correct": "A",
    "explain": "Well-Architectedの信頼性にも通じる。"
  },
  {
    "id": 29,
    "domain": "D1",
    "body": "AWSの無料利用枠の説明として正しいものはどれか。",
    "choice_a": "データ送信は常に無制限無料",
    "choice_b": "サービスと期間・量に条件がある",
    "choice_c": "全サービスが永久に無料",
    "choice_d": "企業アカウントでは使えない",
    "correct": "B",
    "explain": "Free Tierは条件付き。"
  },
  {
    "id": 30,
    "domain": "D1",
    "body": "TCO（総所有コスト）をクラウドと比較するとき含めるべきものはどれか。",
    "choice_a": "ドメイン名だけ",
    "choice_b": "キーボード代だけ",
    "choice_c": "ハードウェアだけでなく電力・設置・運用人件費",
    "choice_d": "インスタンス料金だけ",
    "correct": "C",
    "explain": "オンプレは隠れた運用費が多い。"
  },
  {
    "id": 31,
    "domain": "D1",
    "body": "クラウド利用で「トレードオフ」として正しいものはどれか。",
    "choice_a": "セキュリティ作業が完全に不要になる",
    "choice_b": "障害が絶対に起きない",
    "choice_c": "IAMは使わなくてよい",
    "choice_d": "利便性と、設定ミスによる公開リスクが同居する",
    "correct": "D",
    "explain": "責任は共有。便利さの裏に設定責任がある。"
  },
  {
    "id": 32,
    "domain": "D1",
    "body": "リフトアンドシフト（Rehost）に近い説明はどれか。",
    "choice_a": "既存サーバをほぼそのままクラウドのVMへ移す",
    "choice_b": "アプリを最初から作り直す",
    "choice_c": "サービスを廃止する",
    "choice_d": "オンプレに戻すこと",
    "correct": "A",
    "explain": "移行戦略の一つ。最適化は後から。"
  },
  {
    "id": 33,
    "domain": "D1",
    "body": "AWSが顧客に提供する価値として適切なものはどれか。",
    "choice_a": "必ず利益を保証する",
    "choice_b": "必要なときに必要なだけITリソースを使える",
    "choice_c": "顧客企業の人事評価を代行する",
    "choice_d": "店舗の接客を代行する",
    "correct": "B",
    "explain": "オンデマンドのITリソース。"
  },
  {
    "id": 34,
    "domain": "D1",
    "body": "「可用性」と「耐久性」の違いとして適切なものはどれか。",
    "choice_a": "耐久性はCPU性能のこと",
    "choice_b": "可用性は請求金額のこと",
    "choice_c": "可用性は今使えること、耐久性はデータが失われにくいこと",
    "choice_d": "同じ意味である",
    "correct": "C",
    "explain": "S3の11ナインは耐久性の話としてよく出る。"
  },
  {
    "id": 35,
    "domain": "D1",
    "body": "クラウドでイノベーションが加速する理由はどれか。",
    "choice_a": "変更は年次リリースに限られる",
    "choice_b": "実験には必ずハードウェア購入が要る",
    "choice_c": "失敗が許されない契約だけ",
    "choice_d": "新サービスを小さく始めてすぐ止められる",
    "correct": "D",
    "explain": "小さく試せる。"
  },
  {
    "id": 36,
    "domain": "D1",
    "body": "AWSリージョンを複数使う利点でないものはどれか。",
    "choice_a": "単一インスタンスのCPUクロックが必ず2倍になる",
    "choice_b": "災害対策",
    "choice_c": "低レイテンシ",
    "choice_d": "データ主権への対応",
    "correct": "A",
    "explain": "リージョンを増やすこと自体はCPUを速くしない。"
  },
  {
    "id": 37,
    "domain": "D1",
    "body": "運用上の優秀性（Operational Excellence）で重視することはどれか。",
    "choice_a": "変更を隠す",
    "choice_b": "運用をコード化し、改善し続ける",
    "choice_c": "手動作業を増やす",
    "choice_d": "ログを残さない",
    "correct": "B",
    "explain": "Well-Architectedの柱の一つ。"
  },
  {
    "id": 38,
    "domain": "D1",
    "body": "セキュリティの柱で最初に考えるべきことはどれか。",
    "choice_a": "ルートユーザーを共有する",
    "choice_b": "暗号化を無効にする",
    "choice_c": "誰が何にアクセスできるかを設計する",
    "choice_d": "すべてのポートを開ける",
    "correct": "C",
    "explain": "IAMと最小権限が起点。"
  },
  {
    "id": 39,
    "domain": "D1",
    "body": "コスト最適化の柱で行うことはどれか。",
    "choice_a": "常にオンデマンド最大構成にする",
    "choice_b": "請求を見ない",
    "choice_c": "Reservedを禁止する",
    "choice_d": "使っていないリソースを止める・サイズを見直す",
    "correct": "D",
    "explain": "可視化して無駄を消す。"
  },
  {
    "id": 40,
    "domain": "D1",
    "body": "クラウドのデプロイメントモデルに含まれないものはどれか。",
    "choice_a": "紙の台帳だけを使うモデル",
    "choice_b": "パブリッククラウド",
    "choice_c": "ハイブリッド",
    "choice_d": "オンプレミス",
    "correct": "A",
    "explain": "試験では cloud / hybrid / on-premises。"
  },
  {
    "id": 41,
    "domain": "D1",
    "body": "AWSの利用者がコードなしで操作する主な手段はどれか。",
    "choice_a": "ルートパスワードを掲示する",
    "choice_b": "マネジメントコンソール",
    "choice_c": "必ずC++でSDKを書く",
    "choice_d": "データセンターのラックを開ける",
    "correct": "B",
    "explain": "コンソール、CLI、SDKが操作手段。"
  },
  {
    "id": 42,
    "domain": "D1",
    "body": "自動化の利点として適切なものはどれか。",
    "choice_a": "監査ができなくなる",
    "choice_b": "ロールバックできなくなる",
    "choice_c": "人的ミスを減らし再現性を上げる",
    "choice_d": "必ずコストが上がる",
    "correct": "C",
    "explain": "IaCやAuto Scaling。"
  },
  {
    "id": 43,
    "domain": "D1",
    "body": "「従量課金なのに想定より高い」ときまず疑うことはどれか。",
    "choice_a": "AWSが誤請求していると決めつける",
    "choice_b": "IAMを消す",
    "choice_c": "VPCを全削除する",
    "choice_d": "起動しっぱなし・データ送信・想定外のAZ間転送",
    "correct": "D",
    "explain": "Cost Explorerで内訳を見る。"
  },
  {
    "id": 44,
    "domain": "D1",
    "body": "クラウドの利点「キャパシティの推測が不要に近い」とはどういう意味か。",
    "choice_a": "ピークに合わせて買い切らず、必要分を伸ばせる",
    "choice_b": "容量制限が一切ない",
    "choice_c": "ディスクが無限で無料",
    "choice_d": "監視が不要",
    "correct": "A",
    "explain": "需要予測の失敗を吸収しやすい。"
  },
  {
    "id": 45,
    "domain": "D1",
    "body": "AWSパートナーネットワーク（APN）の役割として適切なものはどれか。",
    "choice_a": "ルートユーザーの別名",
    "choice_b": "導入や製品で顧客を支援するパートナー企業の仕組み",
    "choice_c": "EC2の内部CPU名",
    "choice_d": "S3のストレージクラス",
    "correct": "B",
    "explain": "コンサル・SaaSベンダーなど。"
  },
  {
    "id": 46,
    "domain": "D1",
    "body": "AWS Professional Servicesの説明として近いものはどれか。",
    "choice_a": "S3の保管クラス",
    "choice_b": "VPCのサブネット種別",
    "choice_c": "AWSの専門チームによる有償の支援",
    "choice_d": "無料のメールサポートだけ",
    "correct": "C",
    "explain": "大規模移行などで入る支援。"
  },
  {
    "id": 47,
    "domain": "D1",
    "body": "ホワイトペーパーや公式ドキュメントを探す場所として適切なものはどれか。",
    "choice_a": "任意の掲示板の噂だけ",
    "choice_b": "ルートユーザーの秘密の質問",
    "choice_c": "S3バケット名",
    "choice_d": "AWSの公式サイト（ドキュメント / ホワイトペーパー）",
    "correct": "D",
    "explain": "試験でも公式情報源が問われる。"
  },
  {
    "id": 48,
    "domain": "D1",
    "body": "クラウド移行で増えることが多い責任はどれか。",
    "choice_a": "IAMや設定ミスを防ぐガバナンス",
    "choice_b": "データセンターの建物警備",
    "choice_c": "サーバの電源工事",
    "choice_d": "冷却設備の購入",
    "correct": "A",
    "explain": "物理はAWS、設定とデータは顧客。"
  },
  {
    "id": 49,
    "domain": "D2",
    "body": "責任共有モデルでAWSが責任を持つものはどれか。",
    "choice_a": "セキュリティグループのルール",
    "choice_b": "データセンターの物理セキュリティ",
    "choice_c": "顧客が置いたデータの分類",
    "choice_d": "IAMユーザーのパスワード",
    "correct": "B",
    "explain": "建物・ハードウェアはAWS。データとIAMは顧客。"
  },
  {
    "id": 50,
    "domain": "D2",
    "body": "EC2利用時に顧客が責任を持つものはどれか。",
    "choice_a": "リージョンの建物",
    "choice_b": "ホストハードウェア",
    "choice_c": "ゲストOSのパッチ適用",
    "choice_d": "ハイパーバイザの管理",
    "correct": "C",
    "explain": "IaaSではOSより上が顧客。"
  },
  {
    "id": 51,
    "domain": "D2",
    "body": "RDS利用時にAWSが責任を持つ範囲として適切なものはどれか。",
    "choice_a": "テーブル内の個人情報の中身",
    "choice_b": "アプリのSQLの正しさ",
    "choice_c": "IAMユーザーの退職処理",
    "choice_d": "DBエンジンのパッチや基盤OS",
    "correct": "D",
    "explain": "PaaSなのでエンジンまでAWS。データは顧客。"
  },
  {
    "id": 52,
    "domain": "D2",
    "body": "Lambda利用時に顧客が主に責任を持つものはどれか。",
    "choice_a": "関数コードと権限設定",
    "choice_b": "データセンターの入退室",
    "choice_c": "物理サーバの交換",
    "choice_d": "ラックの電源",
    "correct": "A",
    "explain": "サーバレスでもコードとIAMは自分。"
  },
  {
    "id": 53,
    "domain": "D2",
    "body": "ルートユーザーの正しい扱い方はどれか。",
    "choice_a": "MFAは不要",
    "choice_b": "MFAを有効にし、日常作業では使わない",
    "choice_c": "全員でパスワードを共有する",
    "choice_d": "アクセスキーを公開リポジトリに置く",
    "correct": "B",
    "explain": "Rootは最強。日常はIAM。"
  },
  {
    "id": 54,
    "domain": "D2",
    "body": "IAMユーザーとIAMロールの違いとして適切なものはどれか。",
    "choice_a": "ユーザーはEC2にしか付けられない",
    "choice_b": "ロールはルート専用である",
    "choice_c": "ロールは一時的な認証情報を引き受けられる",
    "choice_d": "ロールは人にだけ付く長期パスワードである",
    "correct": "C",
    "explain": "EC2や他アカウントはロール。人はユーザーが多い。"
  },
  {
    "id": 55,
    "domain": "D2",
    "body": "IAMグループの用途として適切なものはどれか。",
    "choice_a": "EC2インスタンスを起動する",
    "choice_b": "S3のストレージクラスを変える",
    "choice_c": "AZを増やす",
    "choice_d": "同じ権限を複数ユーザーにまとめて付ける",
    "correct": "D",
    "explain": "権限のまとめ役。"
  },
  {
    "id": 56,
    "domain": "D2",
    "body": "最小権限の原則とはどれか。",
    "choice_a": "仕事に必要な権限だけを与える",
    "choice_b": "全サービスをAdministratorAccessにする",
    "choice_c": "全員をルートにする",
    "choice_d": "ポリシーを付けない",
    "correct": "A",
    "explain": "Least privilege。"
  },
  {
    "id": 57,
    "domain": "D2",
    "body": "操作ログ（誰がどのAPIを呼んだか）を残すサービスはどれか。",
    "choice_a": "Amazon RDS",
    "choice_b": "AWS CloudTrail",
    "choice_c": "Amazon CloudWatch",
    "choice_d": "Amazon S3",
    "correct": "B",
    "explain": "監査はTrail。監視はWatch。"
  },
  {
    "id": 58,
    "domain": "D2",
    "body": "CPU使用率のアラームを出すのに使うサービスはどれか。",
    "choice_a": "AWS Artifact",
    "choice_b": "AWS WAF",
    "choice_c": "Amazon CloudWatch",
    "choice_d": "AWS CloudTrail",
    "correct": "C",
    "explain": "メトリクスとアラームはCloudWatch。"
  },
  {
    "id": 59,
    "domain": "D2",
    "body": "リソースの設定がルールに準拠しているかを記録・評価するのはどれか。",
    "choice_a": "Amazon Polly",
    "choice_b": "Amazon SNS",
    "choice_c": "Amazon Lightsail",
    "choice_d": "AWS Config",
    "correct": "D",
    "explain": "構成履歴とコンプライアンスはConfig。"
  },
  {
    "id": 60,
    "domain": "D2",
    "body": "DDoSからAWS上のアプリを守る基本サービスはどれか。",
    "choice_a": "AWS Shield",
    "choice_b": "Amazon RDS",
    "choice_c": "AWS Glue",
    "choice_d": "Amazon Athena",
    "correct": "A",
    "explain": "Shield Standardは標準で有効。Web攻撃はWAF。"
  },
  {
    "id": 61,
    "domain": "D2",
    "body": "SQLインジェクションなどのWeb攻撃をフィルタするのはどれか。",
    "choice_a": "Amazon EFS",
    "choice_b": "AWS WAF",
    "choice_c": "AWS Shield Standardだけ",
    "choice_d": "Amazon CloudFrontの料金クラス",
    "correct": "B",
    "explain": "WAFはWeb ACL。ShieldはDDoS。"
  },
  {
    "id": 62,
    "domain": "D2",
    "body": "暗号鍵を管理する中心的なサービスはどれか。",
    "choice_a": "Amazon SQS",
    "choice_b": "AWS Snowball",
    "choice_c": "AWS KMS",
    "choice_d": "Amazon Route 53",
    "correct": "C",
    "explain": "KMS。専用HSMが必要ならCloudHSM。"
  },
  {
    "id": 63,
    "domain": "D2",
    "body": "コンプライアンスレポート（SOCなど）を入手する場所はどれか。",
    "choice_a": "Amazon Macie",
    "choice_b": "Amazon Inspector",
    "choice_c": "AWS Batch",
    "choice_d": "AWS Artifact",
    "correct": "D",
    "explain": "Artifactは監査資料のポータル。"
  },
  {
    "id": 64,
    "domain": "D2",
    "body": "怪しい通信や脅威を知能的に検知するのはどれか。",
    "choice_a": "Amazon GuardDuty",
    "choice_b": "Amazon Inspector",
    "choice_c": "AWS Glue",
    "choice_d": "Amazon Redshift",
    "correct": "A",
    "explain": "GuardDutyは脅威。Inspectorは脆弱性。"
  },
  {
    "id": 65,
    "domain": "D2",
    "body": "EC2の脆弱性をスキャンするのに適するのはどれか。",
    "choice_a": "Amazon QuickSight",
    "choice_b": "Amazon Inspector",
    "choice_c": "Amazon GuardDuty",
    "choice_d": "Amazon Polly",
    "correct": "B",
    "explain": "穴を探すのがInspector。"
  },
  {
    "id": 66,
    "domain": "D2",
    "body": "複数のセキュリティ発見を集約するサービスはどれか。",
    "choice_a": "AWS Snowcone",
    "choice_b": "Amazon Connect",
    "choice_c": "AWS Security Hub",
    "choice_d": "Amazon Lightsail",
    "correct": "C",
    "explain": "ハブとして一覧化する。"
  },
  {
    "id": 67,
    "domain": "D2",
    "body": "S3内の個人情報などの機密データを見つけるサービスはどれか。",
    "choice_a": "Amazon CloudFront",
    "choice_b": "AWS Elastic Beanstalk",
    "choice_c": "Amazon EBS",
    "choice_d": "Amazon Macie",
    "correct": "D",
    "explain": "MacieはMLでPII検出。"
  },
  {
    "id": 68,
    "domain": "D2",
    "body": "セキュリティグループの特徴として正しいものはどれか。",
    "choice_a": "ステートフルで、許可した通信の戻りは自動許可",
    "choice_b": "ステートレスで往復とも手動許可が必要",
    "choice_c": "サブネットにだけ付く",
    "choice_d": "デフォルトですべて許可",
    "correct": "A",
    "explain": "SGはインスタンス（ENI）前。デフォルトは inbound 拒否。"
  },
  {
    "id": 69,
    "domain": "D2",
    "body": "ネットワークACLの特徴として正しいものはどれか。",
    "choice_a": "S3の暗号化方式である",
    "choice_b": "ステートレスでサブネット単位",
    "choice_c": "ステートフルでインスタンス単位",
    "choice_d": "IAMユーザーに付ける",
    "correct": "B",
    "explain": "NACLはサブネット。往復ルールが必要。"
  },
  {
    "id": 70,
    "domain": "D2",
    "body": "パスワードやAPIキーをコードに直書きしないために使うものはどれか。",
    "choice_a": "セキュリティグループ",
    "choice_b": "Auto Scaling",
    "choice_c": "AWS Secrets Manager",
    "choice_d": "Amazon CloudWatch Logsだけ",
    "correct": "C",
    "explain": "SSM Parameter Storeでも可。"
  },
  {
    "id": 71,
    "domain": "D2",
    "body": "複数アカウントでSSOを実現するのに適するものはどれか。",
    "choice_a": "Amazon S3 Glacier",
    "choice_b": "Amazon SQS",
    "choice_c": "AWS Batch",
    "choice_d": "IAM Identity Center",
    "correct": "D",
    "explain": "旧AWS SSO。"
  },
  {
    "id": 72,
    "domain": "D2",
    "body": "暗号化の「保管時」と「転送時」の説明として正しいものはどれか。",
    "choice_a": "保管時は保存データ、転送時は通信経路",
    "choice_b": "どちらもCPU性能のこと",
    "choice_c": "保管時はVPCだけを指す",
    "choice_d": "転送時はEBSスナップショットだけ",
    "correct": "A",
    "explain": "in transit / at rest。"
  },
  {
    "id": 73,
    "domain": "D2",
    "body": "Shield Advancedの説明として適切なものはどれか。",
    "choice_a": "RDSのバックアップ",
    "choice_b": "有償で、より高度なDDoS保護とサポートがある",
    "choice_c": "全アカウントで無償の標準機能だけ",
    "choice_d": "S3の公開設定",
    "correct": "B",
    "explain": "Standardは無料、Advancedは有料。"
  },
  {
    "id": 74,
    "domain": "D2",
    "body": "Trusted Advisorが診断するカテゴリに含まれないものはどれか。",
    "choice_a": "セキュリティ",
    "choice_b": "耐障害性",
    "choice_c": "人事評価",
    "choice_d": "コスト最適化",
    "correct": "C",
    "explain": "コスト・パフォーマンス・セキュリティ・耐障害性・サービス制限。"
  },
  {
    "id": 75,
    "domain": "D2",
    "body": "MFAの目的はどれか。",
    "choice_a": "請求を安くする",
    "choice_b": "AZを増やす",
    "choice_c": "S3クラスを変える",
    "choice_d": "パスワード以外の要素を足してなりすましを難しくする",
    "correct": "D",
    "explain": "多要素認証。Rootは必須級。"
  },
  {
    "id": 76,
    "domain": "D2",
    "body": "クロスアカウントアクセスでよく使うものはどれか。",
    "choice_a": "IAMロールの引き受け",
    "choice_b": "ルートパスワードの共有",
    "choice_c": "EBSの暗号化解除",
    "choice_d": "CloudFrontの無効化",
    "correct": "A",
    "explain": "ロール＋信頼ポリシー。"
  },
  {
    "id": 77,
    "domain": "D2",
    "body": "バケットを公開しすぎないために顧客が行うことはどれか。",
    "choice_a": "CloudTrailを止める",
    "choice_b": "S3のブロックパブリックアクセスとポリシーを確認する",
    "choice_c": "AWSに建物警備を任せるだけ",
    "choice_d": "KMSを削除する",
    "correct": "B",
    "explain": "設定は顧客責任。"
  },
  {
    "id": 78,
    "domain": "D2",
    "body": "AWS Marketplaceからセキュリティ製品を買うことができる。この説明はどれか。",
    "choice_a": "誤り。MarketplaceはEC2専用",
    "choice_b": "誤り。請求と無関係",
    "choice_c": "正しい。サードパーティ製品を利用できる",
    "choice_d": "誤り。AWS純正以外は禁止",
    "correct": "C",
    "explain": "試験ガイドにもMarketplaceが出る。"
  },
  {
    "id": 79,
    "domain": "D2",
    "body": "CloudTrailとCloudWatchの使い分けはどれか。",
    "choice_a": "どちらも同じ",
    "choice_b": "TrailはCPU専用、Watchは監査専用",
    "choice_c": "Watchは鍵管理",
    "choice_d": "Trailは監査、Watchは監視",
    "correct": "D",
    "explain": "最頻出の対比。"
  },
  {
    "id": 80,
    "domain": "D2",
    "body": "アクセスキーの扱いとして適切なものはどれか。",
    "choice_a": "漏洩したら無効化し、長期キーは最小限にする",
    "choice_b": "GitHubにコミットする",
    "choice_c": "Slackに貼る",
    "choice_d": "ルートのアクセスキーを常用する",
    "correct": "A",
    "explain": "ロールの方が安全な場面が多い。"
  },
  {
    "id": 81,
    "domain": "D2",
    "body": "セキュリティのベストプラクティスとして適切なものはどれか。",
    "choice_a": "ログを残さない",
    "choice_b": "ルートはMFA、日常はIAM、権限は最小",
    "choice_c": "全員Administrator",
    "choice_d": "SGですべて0.0.0.0/0の22番を常時開放",
    "correct": "B",
    "explain": "基本セット。"
  },
  {
    "id": 82,
    "domain": "D2",
    "body": "AWSが責任を持つ「クラウドのセキュリティ」に含まれるものはどれか。",
    "choice_a": "IAMグループ設計",
    "choice_b": "データの分類ラベル",
    "choice_c": "ハイパーバイザや施設の制御",
    "choice_d": "顧客アプリのバグ修正すべて",
    "correct": "C",
    "explain": "of the cloud はAWS。in the cloud は顧客。"
  },
  {
    "id": 83,
    "domain": "D2",
    "body": "顧客が責任を持つ「クラウド内のセキュリティ」に含まれるものはどれか。",
    "choice_a": "リージョンの建物",
    "choice_b": "冷却装置",
    "choice_c": "物理ディスクの廃棄手順（AWS設備）",
    "choice_d": "ゲストOS、ネットワーク設定、データの暗号化選択",
    "correct": "D",
    "explain": "in the cloud。"
  },
  {
    "id": 84,
    "domain": "D2",
    "body": "AWS ConfigとCloudTrailの違いとして適切なものはどれか。",
    "choice_a": "Configは設定の状態、Trailは操作の履歴",
    "choice_b": "ConfigはDDoS対策",
    "choice_c": "TrailはS3クラス",
    "choice_d": "同じサービスである",
    "correct": "A",
    "explain": "「今どうなっているか」と「誰が何をしたか」。"
  },
  {
    "id": 85,
    "domain": "D2",
    "body": "WAFを置く位置としてよくあるものはどれか。",
    "choice_a": "Route 53のホストゾーン名",
    "choice_b": "CloudFrontやALBの前",
    "choice_c": "RDSの中",
    "choice_d": "KMSの鍵の中",
    "correct": "B",
    "explain": "HTTPを見る場所。"
  },
  {
    "id": 86,
    "domain": "D2",
    "body": "Inspectorが見つけるものに近いのはどれか。",
    "choice_a": "S3のストレージクラス",
    "choice_b": "Route 53のレイテンシルーティング",
    "choice_c": "ソフトウェアの既知の脆弱性やネットワーク露出",
    "choice_d": "先月の請求額",
    "correct": "C",
    "explain": "CVEなどの脆弱性。"
  },
  {
    "id": 87,
    "domain": "D2",
    "body": "GuardDutyの入力になるものとして適切なものはどれか。",
    "choice_a": "Wordの履歴書",
    "choice_b": "オンプレの冷却ログだけ",
    "choice_c": "キーボード配列",
    "choice_d": "CloudTrailやVPCフローログなどのテレメトリ",
    "correct": "D",
    "explain": "既存ログを解析して脅威を出す。"
  },
  {
    "id": 88,
    "domain": "D2",
    "body": "S3のサーバサイド暗号化でよく使うものはどれか。",
    "choice_a": "SSE-S3 または SSE-KMS",
    "choice_b": "Shield Advanced",
    "choice_c": "Auto Scaling",
    "choice_d": "Elastic Beanstalk",
    "correct": "A",
    "explain": "保管時の暗号化。"
  },
  {
    "id": 89,
    "domain": "D2",
    "body": "HTTPSで通信を暗号化するのはどれに当たるか。",
    "choice_a": "コスト配分タグ",
    "choice_b": "転送時の暗号化",
    "choice_c": "保管時の暗号化だけ",
    "choice_d": "物理セキュリティ",
    "correct": "B",
    "explain": "in transit。"
  },
  {
    "id": 90,
    "domain": "D2",
    "body": "IAMポリシーでDenyがあるときの考え方として適切なものはどれか。",
    "choice_a": "ポリシーは無視される",
    "choice_b": "ルートだけがDenyを無視できるわけではない（通常）",
    "choice_c": "明示的Denyは許可より優先される",
    "choice_d": "Allowが必ず勝つ",
    "correct": "C",
    "explain": "明示的拒否が強い。"
  },
  {
    "id": 91,
    "domain": "D2",
    "body": "パスワードポリシーを設定する場所として適切なものはどれか。",
    "choice_a": "Amazon S3 Glacier",
    "choice_b": "Amazon SQS",
    "choice_c": "AWS Glue",
    "choice_d": "IAMのアカウント設定",
    "correct": "D",
    "explain": "IAMで長さや複雑さを要求できる。"
  },
  {
    "id": 92,
    "domain": "D2",
    "body": "AWSアカウントを守る最初の手順として優先度が高いものはどれか。",
    "choice_a": "ルートにMFA、アクセスキーを作らない",
    "choice_b": "全ポート開放",
    "choice_c": "CloudTrailを無効",
    "choice_d": "パブリックS3を推奨",
    "correct": "A",
    "explain": "初期セキュア化。"
  },
  {
    "id": 93,
    "domain": "D2",
    "body": "VPCフローログの用途はどれか。",
    "choice_a": "Lambdaをデプロイする",
    "choice_b": "ENIを流れるIPトラフィックを記録する",
    "choice_c": "請求を安くする",
    "choice_d": "AMIをコピーする",
    "correct": "B",
    "explain": "通信の受け入れ/拒否の記録。"
  },
  {
    "id": 94,
    "domain": "D2",
    "body": "セキュリティ情報の公式な入手先として適切なものはどれか。",
    "choice_a": "ルートユーザーの秘密の質問",
    "choice_b": "S3のバケット名",
    "choice_c": "AWS Security の公式ブログやドキュメント",
    "choice_d": "任意のSNSの転載だけ",
    "correct": "C",
    "explain": "試験ガイドでも公式情報源が挙がる。"
  },
  {
    "id": 95,
    "domain": "D2",
    "body": "共有責任がサービスによってずれる例として正しいものはどれか。",
    "choice_a": "Lambdaの方が顧客がハードウェアを管理する",
    "choice_b": "S3では顧客がディスクを交換する",
    "choice_c": "どのサービスも責任範囲は同一",
    "choice_d": "EC2よりRDSの方がAWSの範囲が広い",
    "correct": "D",
    "explain": "マネージド度で境界が動く。"
  },
  {
    "id": 96,
    "domain": "D2",
    "body": "監査対応で「いつ誰が設定を変えたか」を知りたい。使うのはどれか。",
    "choice_a": "CloudTrail（必要ならConfigも）",
    "choice_b": "Amazon Polly",
    "choice_c": "Amazon Translate",
    "choice_d": "Amazon Lightsail",
    "correct": "A",
    "explain": "操作履歴はTrail。"
  },
  {
    "id": 97,
    "domain": "D2",
    "body": "Amazon Cognitoの用途として近いものはどれか。",
    "choice_a": "Redshiftの列圧縮",
    "choice_b": "アプリのエンドユーザー認証",
    "choice_c": "VPCの専用線",
    "choice_d": "EC2のスポット入札",
    "correct": "B",
    "explain": "モバイル/Webのユーザーディレクトリ。CLFでも名前が出る。"
  },
  {
    "id": 98,
    "domain": "D2",
    "body": "AWS Certificate Manager（ACM）の用途はどれか。",
    "choice_a": "S3のGlacier移行",
    "choice_b": "SQSのキュー長",
    "choice_c": "TLS証明書の発行と管理",
    "choice_d": "EC2のCPU課金",
    "correct": "C",
    "explain": "HTTPS用証明書。"
  },
  {
    "id": 99,
    "domain": "D2",
    "body": "パブリックサブネットとプライベートサブネットの違いはどれか。",
    "choice_a": "AZが違うことだけ",
    "choice_b": "IAMの違い",
    "choice_c": "請求通貨の違い",
    "choice_d": "IGW経由で直接インターネットに出られるかどうか",
    "correct": "D",
    "explain": "ルートテーブルとIGW。"
  },
  {
    "id": 100,
    "domain": "D2",
    "body": "bastion（踏み台）を置く目的はどれか。",
    "choice_a": "プライベートな管理口を限定して公開面を減らす",
    "choice_b": "S3を安くする",
    "choice_c": "RDSを遅くする",
    "choice_d": "CloudFrontを無効にする",
    "correct": "A",
    "explain": "管理用の入口を絞る。"
  },
  {
    "id": 101,
    "domain": "D2",
    "body": "データ分類をしたうえで行うべきことはどれか。",
    "choice_a": "MFAを外す",
    "choice_b": "機密度に応じて暗号化とアクセス制御を変える",
    "choice_c": "すべてをパブリックにする",
    "choice_d": "ログを捨てる",
    "correct": "B",
    "explain": "顧客のデータ責任。"
  },
  {
    "id": 102,
    "domain": "D2",
    "body": "AWS OrganizationsのSCP（サービスコントロールポリシー）のイメージはどれか。",
    "choice_a": "S3のライフサイクル",
    "choice_b": "WAFのルール文だけ",
    "choice_c": "配下アカウントに使える操作の上限を組織でかける",
    "choice_d": "EC2のCPUクレジット",
    "correct": "C",
    "explain": "CLFでは名前と「組織のガードレール」が分かればよい。"
  },
  {
    "id": 103,
    "domain": "D2",
    "body": "インシデントが起きたときログが無いと困る理由はどれか。",
    "choice_a": "AZが増える",
    "choice_b": "料金が下がる",
    "choice_c": "証明書が自動更新される",
    "choice_d": "誰が何をしたか追跡できない",
    "correct": "D",
    "explain": "CloudTrail/CloudWatchを先に有効化する。"
  },
  {
    "id": 104,
    "domain": "D2",
    "body": "セキュリティグループで「22番を全世界に開放」するリスクはどれか。",
    "choice_a": "SSHがインターネットから狙われる",
    "choice_b": "S3の耐久性が下がる",
    "choice_c": "KMSが使えなくなる",
    "choice_d": "Route 53が停止する",
    "correct": "A",
    "explain": "管理ポートは制限する。"
  },
  {
    "id": 105,
    "domain": "D2",
    "body": "AWSが提供するコンプライアンスプログラムの情報はどこで確認するか。",
    "choice_a": "Lambdaのタイムアウト",
    "choice_b": "AWS Artifact や公式のコンプライアンスページ",
    "choice_c": "EC2のスポット価格画面だけ",
    "choice_d": "S3の署名付きURLだけ",
    "correct": "B",
    "explain": "地域や業界の要件は顧客が確認する。"
  },
  {
    "id": 106,
    "domain": "D2",
    "body": "暗号化キーのローテーションを支援するのはどれか。",
    "choice_a": "Amazon SQS",
    "choice_b": "Amazon CloudFrontの価格クラス",
    "choice_c": "KMS",
    "choice_d": "Amazon SNS",
    "correct": "C",
    "explain": "キー管理はKMS。"
  },
  {
    "id": 107,
    "domain": "D2",
    "body": "「クラウドのセキュリティはAWS、クラウド内は顧客」という整理の意味はどれか。",
    "choice_a": "全部AWS",
    "choice_b": "全部顧客がデータセンターを持つ",
    "choice_c": "セキュリティは不要",
    "choice_d": "基盤はAWS、設定とデータは自分",
    "correct": "D",
    "explain": "責任共有の要約。"
  },
  {
    "id": 108,
    "domain": "D2",
    "body": "IAM Access Analyzerの用途に近いものはどれか。",
    "choice_a": "外部に共有されているリソースを見つける",
    "choice_b": "EC2のCPUを上げる",
    "choice_c": "Glacierから取り出す",
    "choice_d": "ELBのアルゴリズムを変える",
    "correct": "A",
    "explain": "意図しない公開の発見。"
  },
  {
    "id": 109,
    "domain": "D3",
    "body": "AWSリージョンの説明として正しいものはどれか。",
    "choice_a": "S3の1ファイル",
    "choice_b": "地理的に分かれた複数AZのまとまり",
    "choice_c": "1台のサーバの別名",
    "choice_d": "IAMユーザーの種類",
    "correct": "B",
    "explain": "東京リージョンなど。"
  },
  {
    "id": 110,
    "domain": "D3",
    "body": "アベイラビリティーゾーン（AZ）の説明はどれか。",
    "choice_a": "請求書の項目",
    "choice_b": "ルートユーザーのMFA装置",
    "choice_c": "リージョン内の独立した障害領域",
    "choice_d": "世界中のCDN拠点",
    "correct": "C",
    "explain": "複数AZでHA。"
  },
  {
    "id": 111,
    "domain": "D3",
    "body": "エッジロケーションを主に使うサービスはどれか。",
    "choice_a": "Amazon RDS",
    "choice_b": "Amazon EFS",
    "choice_c": "AWS Glue",
    "choice_d": "Amazon CloudFront",
    "correct": "D",
    "explain": "ユーザーに近いキャッシュ。Route 53もエッジを使う。"
  },
  {
    "id": 112,
    "domain": "D3",
    "body": "仮想サーバを自分で持つサービスはどれか。",
    "choice_a": "Amazon EC2",
    "choice_b": "AWS Lambda",
    "choice_c": "Amazon S3",
    "choice_d": "Amazon DynamoDB",
    "correct": "A",
    "explain": "IaaSの代表。"
  },
  {
    "id": 113,
    "domain": "D3",
    "body": "イベント駆動で短時間コードを実行するのに適するのはどれか。",
    "choice_a": "AWS Direct Connect",
    "choice_b": "AWS Lambda",
    "choice_c": "Amazon EC2専用ホストだけ",
    "choice_d": "Amazon EBS",
    "correct": "B",
    "explain": "サーバレス。"
  },
  {
    "id": 114,
    "domain": "D3",
    "body": "KubernetesをAWSで動かしたいときのサービスはどれか。",
    "choice_a": "Amazon CloudFront",
    "choice_b": "AWS Artifact",
    "choice_c": "Amazon EKS",
    "choice_d": "Amazon S3",
    "correct": "C",
    "explain": "ECSはAWS独自オーケストレーション、EKSはK8s。"
  },
  {
    "id": 115,
    "domain": "D3",
    "body": "コンテナのオーケストレーションをAWSネイティブで行うのはどれか。",
    "choice_a": "Amazon RDS",
    "choice_b": "Amazon Macie",
    "choice_c": "AWS Shield",
    "choice_d": "Amazon ECS",
    "correct": "D",
    "explain": "ECS。サーバを見たくなければFargate。"
  },
  {
    "id": 116,
    "domain": "D3",
    "body": "コンテナでサーバ（インスタンス）を管理したくないときに使うのはどれか。",
    "choice_a": "AWS Fargate",
    "choice_b": "Amazon EC2だけ",
    "choice_c": "Amazon EBS",
    "choice_d": "AWS Snowball",
    "correct": "A",
    "explain": "ECS/EKSの起動タイプ。"
  },
  {
    "id": 117,
    "domain": "D3",
    "body": "コードをアップロードしてインフラ運用を任せるPaaSはどれか。",
    "choice_a": "AWS WAF",
    "choice_b": "AWS Elastic Beanstalk",
    "choice_c": "AWS CloudTrail",
    "choice_d": "Amazon GuardDuty",
    "correct": "B",
    "explain": "アプリを載せる。"
  },
  {
    "id": 118,
    "domain": "D3",
    "body": "かんたんにVPS的に始めるサービスはどれか。",
    "choice_a": "AWS Config",
    "choice_b": "Amazon Macie",
    "choice_c": "Amazon Lightsail",
    "choice_d": "AWS Organizations",
    "correct": "C",
    "explain": "入門・小さなWeb。"
  },
  {
    "id": 119,
    "domain": "D3",
    "body": "オブジェクトストレージはどれか。",
    "choice_a": "Amazon EBS",
    "choice_b": "Amazon EFS",
    "choice_c": "Amazon RDS",
    "choice_d": "Amazon S3",
    "correct": "D",
    "explain": "バケットにオブジェクト。"
  },
  {
    "id": 120,
    "domain": "D3",
    "body": "EC2に付ける永続ディスクはどれか。",
    "choice_a": "Amazon EBS",
    "choice_b": "Amazon S3",
    "choice_c": "Amazon CloudFront",
    "choice_d": "Amazon SNS",
    "correct": "A",
    "explain": "同じAZ。止めても残る。"
  },
  {
    "id": 121,
    "domain": "D3",
    "body": "止めると消える一時ディスクはどれか。",
    "choice_a": "EFS",
    "choice_b": "インスタンスストア",
    "choice_c": "EBS",
    "choice_d": "S3 Standard",
    "correct": "B",
    "explain": "エフェメラル。"
  },
  {
    "id": 122,
    "domain": "D3",
    "body": "複数AZのEC2から同時にマウントするNFSはどれか。",
    "choice_a": "インスタンスストア",
    "choice_b": "Amazon Glacier Deep Archive",
    "choice_c": "Amazon EFS",
    "choice_d": "Amazon EBS",
    "correct": "C",
    "explain": "共有ファイル。"
  },
  {
    "id": 123,
    "domain": "D3",
    "body": "アーカイブで最安クラスに近いS3はどれか。",
    "choice_a": "S3 Standard",
    "choice_b": "S3 Intelligent-Tieringの即時層だけ",
    "choice_c": "EBS gp3",
    "choice_d": "S3 Glacier Deep Archive",
    "correct": "D",
    "explain": "取り出しに最大12時間かかる想定。"
  },
  {
    "id": 124,
    "domain": "D3",
    "body": "アクセス頻度が分からないときに向きのS3クラスはどれか。",
    "choice_a": "S3 Intelligent-Tiering",
    "choice_b": "S3 Glacier Deep Archive固定",
    "choice_c": "インスタンスストア",
    "choice_d": "EBS Magneticのみ",
    "correct": "A",
    "explain": "自動で階層が動く。"
  },
  {
    "id": 125,
    "domain": "D3",
    "body": "リレーショナルDBのマネージドはどれか。",
    "choice_a": "AWS WAF",
    "choice_b": "Amazon RDS",
    "choice_c": "Amazon S3",
    "choice_d": "Amazon CloudFront",
    "correct": "B",
    "explain": "MySQLやPostgreSQLなど。"
  },
  {
    "id": 126,
    "domain": "D3",
    "body": "MySQL/PostgreSQL互換で高性能なRDS系はどれか。",
    "choice_a": "Amazon Rekognition",
    "choice_b": "AWS Snowball",
    "choice_c": "Amazon Aurora",
    "choice_d": "Amazon SQS",
    "correct": "C",
    "explain": "Aurora。"
  },
  {
    "id": 127,
    "domain": "D3",
    "body": "キーバリューのNoSQLでミリ秒応答なのはどれか。",
    "choice_a": "Amazon RDS for Oracleだけ",
    "choice_b": "Amazon EFS",
    "choice_c": "AWS Artifact",
    "choice_d": "Amazon DynamoDB",
    "correct": "D",
    "explain": "サーバレスなテーブル。"
  },
  {
    "id": 128,
    "domain": "D3",
    "body": "データウェアハウスはどれか。",
    "choice_a": "Amazon Redshift",
    "choice_b": "Amazon SQS",
    "choice_c": "AWS Shield",
    "choice_d": "Amazon Polly",
    "correct": "A",
    "explain": "分析用の大量集計。"
  },
  {
    "id": 129,
    "domain": "D3",
    "body": "メモリキャッシュはどれか。",
    "choice_a": "Amazon Inspector",
    "choice_b": "Amazon ElastiCache",
    "choice_c": "Amazon S3 Glacier",
    "choice_d": "AWS CloudTrail",
    "correct": "B",
    "explain": "Redis/Memcached。"
  },
  {
    "id": 130,
    "domain": "D3",
    "body": "自分専用の仮想ネットワークはどれか。",
    "choice_a": "AWS KMS",
    "choice_b": "Amazon Macie",
    "choice_c": "Amazon VPC",
    "choice_d": "Amazon S3",
    "correct": "C",
    "explain": "サブネットを切る。"
  },
  {
    "id": 131,
    "domain": "D3",
    "body": "VPCからインターネットへ出すゲートウェイはどれか。",
    "choice_a": "NATゲートウェイだけ",
    "choice_b": "Direct Connect",
    "choice_c": "Storage Gateway",
    "choice_d": "インターネットゲートウェイ",
    "correct": "D",
    "explain": "IGW。"
  },
  {
    "id": 132,
    "domain": "D3",
    "body": "プライベートサブネットから外へ出る（入は直接受けない）のはどれか。",
    "choice_a": "NATゲートウェイ",
    "choice_b": "IGWをサブネットに直結するだけ",
    "choice_c": "CloudFront",
    "choice_d": "KMS",
    "correct": "A",
    "explain": "更新は出られるが、外から直接は来ない。"
  },
  {
    "id": 133,
    "domain": "D3",
    "body": "DNSサービスはどれか。",
    "choice_a": "Amazon EBS",
    "choice_b": "Amazon Route 53",
    "choice_c": "Amazon CloudWatch",
    "choice_d": "AWS Config",
    "correct": "B",
    "explain": "名前解決。"
  },
  {
    "id": 134,
    "domain": "D3",
    "body": "CDNはどれか。",
    "choice_a": "Amazon EFS",
    "choice_b": "AWS Glue",
    "choice_c": "Amazon CloudFront",
    "choice_d": "Amazon RDS",
    "correct": "C",
    "explain": "エッジ配信。"
  },
  {
    "id": 135,
    "domain": "D3",
    "body": "専用線でオンプレとAWSを結ぶのはどれか。",
    "choice_a": "Site-to-Site VPNだけ",
    "choice_b": "Amazon SQS",
    "choice_c": "Amazon SNS",
    "choice_d": "AWS Direct Connect",
    "correct": "D",
    "explain": "安定・帯域。VPNより高いことが多い。"
  },
  {
    "id": 136,
    "domain": "D3",
    "body": "インターネット経由の暗号化接続でオンプレと結ぶのはどれか。",
    "choice_a": "AWS Site-to-Site VPN",
    "choice_b": "Direct Connect専用線だけ",
    "choice_c": "Amazon S3 Standard",
    "choice_d": "Amazon Rekognition",
    "correct": "A",
    "explain": "早く安くつなぐ。"
  },
  {
    "id": 137,
    "domain": "D3",
    "body": "複数EC2へトラフィックを振り分けるのはどれか。",
    "choice_a": "AWS Budgets",
    "choice_b": "Elastic Load Balancing",
    "choice_c": "AWS Artifact",
    "choice_d": "Amazon Macie",
    "correct": "B",
    "explain": "ALB/NLBなど。"
  },
  {
    "id": 138,
    "domain": "D3",
    "body": "負荷に合わせてEC2台数を自動増減するのはどれか。",
    "choice_a": "Amazon Inspector",
    "choice_b": "AWS WAF",
    "choice_c": "Amazon EC2 Auto Scaling",
    "choice_d": "AWS CloudTrail",
    "correct": "C",
    "explain": "弾力性の実装。"
  },
  {
    "id": 139,
    "domain": "D3",
    "body": "インフラをテンプレートで作るIaCはどれか。",
    "choice_a": "Amazon CloudFront",
    "choice_b": "Amazon CloudWatch",
    "choice_c": "AWS CloudTrail",
    "choice_d": "AWS CloudFormation",
    "correct": "D",
    "explain": "名前が似ているので注意。"
  },
  {
    "id": 140,
    "domain": "D3",
    "body": "通知をプッシュ配信（Pub/Sub）するのはどれか。",
    "choice_a": "Amazon SNS",
    "choice_b": "Amazon SQS",
    "choice_c": "Amazon EBS",
    "choice_d": "Amazon RDS",
    "correct": "A",
    "explain": "ファンアウト。"
  },
  {
    "id": 141,
    "domain": "D3",
    "body": "メッセージをキューに溜めて非同期処理するのはどれか。",
    "choice_a": "AWS Shield",
    "choice_b": "Amazon SQS",
    "choice_c": "Amazon SNS",
    "choice_d": "Amazon CloudFront",
    "correct": "B",
    "explain": "疎結合。"
  },
  {
    "id": 142,
    "domain": "D3",
    "body": "S3をSQLでその場検索するのはどれか。",
    "choice_a": "AWS WAF",
    "choice_b": "Amazon Lightsail",
    "choice_c": "Amazon Athena",
    "choice_d": "Amazon EC2",
    "correct": "C",
    "explain": "サーバレスクエリ。"
  },
  {
    "id": 143,
    "domain": "D3",
    "body": "ETL（抽出・変換・ロード）はどれか。",
    "choice_a": "Amazon Route 53",
    "choice_b": "AWS Shield",
    "choice_c": "Amazon Polly",
    "choice_d": "AWS Glue",
    "correct": "D",
    "explain": "データカタログも。"
  },
  {
    "id": 144,
    "domain": "D3",
    "body": "リアルタイムストリーム処理に使うのはどれか。",
    "choice_a": "Amazon Kinesis",
    "choice_b": "Amazon Glacier Deep Archive",
    "choice_c": "AWS Artifact",
    "choice_d": "Amazon EFS",
    "correct": "A",
    "explain": "流れを扱う。"
  },
  {
    "id": 145,
    "domain": "D3",
    "body": "BIダッシュボードはどれか。",
    "choice_a": "Amazon EBS",
    "choice_b": "Amazon QuickSight",
    "choice_c": "Amazon GuardDuty",
    "choice_d": "AWS Snowball",
    "correct": "B",
    "explain": "グラフで見る。"
  },
  {
    "id": 146,
    "domain": "D3",
    "body": "自分でMLモデルを学習・デプロイするのはどれか。",
    "choice_a": "AWS WAF",
    "choice_b": "Amazon SQS",
    "choice_c": "Amazon SageMaker",
    "choice_d": "Amazon S3 Standard-IA",
    "correct": "C",
    "explain": "MLプラットフォーム。"
  },
  {
    "id": 147,
    "domain": "D3",
    "body": "画像や動画の物体・顔などを解析するのはどれか。",
    "choice_a": "Amazon RDS",
    "choice_b": "AWS Direct Connect",
    "choice_c": "Amazon EFS",
    "choice_d": "Amazon Rekognition",
    "correct": "D",
    "explain": "画像認識。"
  },
  {
    "id": 148,
    "domain": "D3",
    "body": "文字を音声にするのはどれか。",
    "choice_a": "Amazon Polly",
    "choice_b": "Amazon Transcribe",
    "choice_c": "Amazon Translate",
    "choice_d": "Amazon Textract",
    "correct": "A",
    "explain": "TTS。"
  },
  {
    "id": 149,
    "domain": "D3",
    "body": "音声を文字にするのはどれか。",
    "choice_a": "Amazon Comprehend",
    "choice_b": "Amazon Transcribe",
    "choice_c": "Amazon Polly",
    "choice_d": "Amazon Translate",
    "correct": "B",
    "explain": "STT。"
  },
  {
    "id": 150,
    "domain": "D3",
    "body": "言語を翻訳するのはどれか。",
    "choice_a": "Amazon Transcribe",
    "choice_b": "Amazon Inspector",
    "choice_c": "Amazon Translate",
    "choice_d": "Amazon Polly",
    "correct": "C",
    "explain": "機械翻訳。"
  },
  {
    "id": 151,
    "domain": "D3",
    "body": "チャットボットを作るのに使うのはどれか。",
    "choice_a": "Amazon Redshift",
    "choice_b": "AWS Shield",
    "choice_c": "Amazon EBS",
    "choice_d": "Amazon Lex",
    "correct": "D",
    "explain": "Alexaと同じ系統。"
  },
  {
    "id": 152,
    "domain": "D3",
    "body": "文章の感情やキーフレーズを取るNLPはどれか。",
    "choice_a": "Amazon Comprehend",
    "choice_b": "Amazon CloudFront",
    "choice_c": "AWS Budgets",
    "choice_d": "Amazon EFS",
    "correct": "A",
    "explain": "テキスト理解。"
  },
  {
    "id": 153,
    "domain": "D3",
    "body": "書類画像から文字・フォームを抜くのはどれか。",
    "choice_a": "Amazon Route 53",
    "choice_b": "Amazon Textract",
    "choice_c": "Amazon Polly",
    "choice_d": "AWS WAF",
    "correct": "B",
    "explain": "OCR。"
  },
  {
    "id": 154,
    "domain": "D3",
    "body": "大量データを物理デバイスで搬送するのはどれか。",
    "choice_a": "Amazon SQS",
    "choice_b": "AWS WAF",
    "choice_c": "AWS Snow Family（Snowball等）",
    "choice_d": "Amazon SNS",
    "correct": "C",
    "explain": "回線が細い・量が多いとき。"
  },
  {
    "id": 155,
    "domain": "D3",
    "body": "データベースをほぼ止めずに移行するのはどれか。",
    "choice_a": "Amazon CloudFront",
    "choice_b": "AWS Shield",
    "choice_c": "Amazon Macie",
    "choice_d": "AWS DMS",
    "correct": "D",
    "explain": "Database Migration Service。"
  },
  {
    "id": 156,
    "domain": "D3",
    "body": "オンプレからAWSストレージを使うゲートウェイはどれか。",
    "choice_a": "AWS Storage Gateway",
    "choice_b": "Internet Gateway",
    "choice_c": "NAT Gateway",
    "choice_d": "Customer Gatewayだけ",
    "correct": "A",
    "explain": "ハイブリッドストレージ。"
  },
  {
    "id": 157,
    "domain": "D3",
    "body": "複数サービスのバックアップを統合するのはどれか。",
    "choice_a": "Amazon Lex",
    "choice_b": "AWS Backup",
    "choice_c": "Amazon Inspector",
    "choice_d": "AWS WAF",
    "correct": "B",
    "explain": "中央管理。"
  },
  {
    "id": 158,
    "domain": "D3",
    "body": "プログラムからAWSを操作する手段はどれか。",
    "choice_a": "ルートのMFAデバイスを分解する",
    "choice_b": "EBSをフォーマットするだけ",
    "choice_c": "AWS CLI または SDK",
    "choice_d": "データセンターの鍵",
    "correct": "C",
    "explain": "コンソール以外。"
  },
  {
    "id": 159,
    "domain": "D3",
    "body": "イベントバスでルールにマッチした処理を走らせるのはどれか。",
    "choice_a": "Amazon EBS",
    "choice_b": "AWS Artifact",
    "choice_c": "Amazon Lightsail",
    "choice_d": "Amazon EventBridge",
    "correct": "D",
    "explain": "スケジュールやSaaSイベントも。"
  },
  {
    "id": 160,
    "domain": "D3",
    "body": "ステップを直列・並列でつなぐワークフローはどれか。",
    "choice_a": "AWS Step Functions",
    "choice_b": "Amazon S3",
    "choice_c": "AWS Shield",
    "choice_d": "Amazon CloudFront",
    "correct": "A",
    "explain": "状態機械。"
  },
  {
    "id": 161,
    "domain": "D3",
    "body": "オンプレにAWSラックを置くサービスはどれか。",
    "choice_a": "Amazon SNS",
    "choice_b": "AWS Outposts",
    "choice_c": "Amazon CloudFront",
    "choice_d": "AWS WAF",
    "correct": "B",
    "explain": "AWSを自社データセンターへ。"
  },
  {
    "id": 162,
    "domain": "D3",
    "body": "大都市の超低遅延ゾーンはどれか。",
    "choice_a": "IAMグループ",
    "choice_b": "Trusted Advisor",
    "choice_c": "AWS Local Zones",
    "choice_d": "S3 Glacier",
    "correct": "C",
    "explain": "リージョン本体よりユーザーに近い。"
  },
  {
    "id": 163,
    "domain": "D3",
    "body": "通信キャリアの5G近くに置くのはどれか。",
    "choice_a": "Amazon RDS",
    "choice_b": "AWS Artifact",
    "choice_c": "Amazon EFS",
    "choice_d": "AWS Wavelength",
    "correct": "D",
    "explain": "モバイル超低遅延。"
  },
  {
    "id": 164,
    "domain": "D3",
    "body": "Hadoop/Sparkのマネージドはどれか。",
    "choice_a": "Amazon EMR",
    "choice_b": "Amazon SQS",
    "choice_c": "AWS Shield",
    "choice_d": "Amazon Polly",
    "correct": "A",
    "explain": "ビッグデータ処理。"
  },
  {
    "id": 165,
    "domain": "D3",
    "body": "社内ドキュメント検索（ML）はどれか。",
    "choice_a": "Amazon Route 53",
    "choice_b": "Amazon Kendra",
    "choice_c": "Amazon EBS",
    "choice_d": "AWS WAF",
    "correct": "B",
    "explain": "エンタープライズ検索。"
  },
  {
    "id": 166,
    "domain": "D3",
    "body": "仮想デスクトップはどれか。",
    "choice_a": "AWS Snowball",
    "choice_b": "Amazon Macie",
    "choice_c": "Amazon WorkSpaces",
    "choice_d": "Amazon S3 Glacier",
    "correct": "C",
    "explain": "DaaS。"
  },
  {
    "id": 167,
    "domain": "D3",
    "body": "CI/CDパイプラインの中心になるサービスはどれか。",
    "choice_a": "Amazon CloudFront",
    "choice_b": "AWS Artifact",
    "choice_c": "Amazon GuardDuty",
    "choice_d": "AWS CodePipeline",
    "correct": "D",
    "explain": "CodeBuild/Deployと組み合わせ。"
  },
  {
    "id": 168,
    "domain": "D3",
    "body": "バッチの大量ジョブを回すのはどれか。",
    "choice_a": "AWS Batch",
    "choice_b": "Amazon CloudFront",
    "choice_c": "AWS WAF",
    "choice_d": "Amazon Artifact",
    "correct": "A",
    "explain": "キューイングしてEC2/Fargateで実行。"
  },
  {
    "id": 169,
    "domain": "D3",
    "body": "S3のライフサイクルポリシーの用途はどれか。",
    "choice_a": "VPCを削除する",
    "choice_b": "日数が経ったオブジェクトを安価なクラスへ移す",
    "choice_c": "EC2のCPUを上げる",
    "choice_d": "IAMユーザーを作る",
    "correct": "B",
    "explain": "Standard → IA → Glacier など。"
  },
  {
    "id": 170,
    "domain": "D3",
    "body": "同じリージョン内の複数AZにRDSを置く目的はどれか。",
    "choice_a": "S3クラスを変える",
    "choice_b": "WAFルールを消す",
    "choice_c": "障害時にフェイルオーバーして可用性を上げる",
    "choice_d": "請求通貨を変える",
    "correct": "C",
    "explain": "Multi-AZ。読み取り増やすならリードレプリカ。"
  },
  {
    "id": 171,
    "domain": "D3",
    "body": "読み取り負荷を分散するRDSの仕組みはどれか。",
    "choice_a": "NATゲートウェイ",
    "choice_b": "Shield Advanced",
    "choice_c": "Cost Explorer",
    "choice_d": "リードレプリカ",
    "correct": "D",
    "explain": "参照をコピーへ。"
  },
  {
    "id": 172,
    "domain": "D3",
    "body": "ALBとNLBの違いの要点はどれか。",
    "choice_a": "ALBはHTTP(L7)、NLBはTCP等(L4)",
    "choice_b": "ALBはデータベース、NLBはDNS",
    "choice_c": "同じものである",
    "choice_d": "NLBはS3専用",
    "correct": "A",
    "explain": "CLFでは層の違いが分かればよい。"
  },
  {
    "id": 173,
    "domain": "D3",
    "body": "CloudFrontのオリジンになりやすいものはどれか。",
    "choice_a": "Trusted Advisor",
    "choice_b": "S3バケットやALB",
    "choice_c": "IAMユーザー",
    "choice_d": "KMSのキーポリシーだけ",
    "correct": "B",
    "explain": "配信元。"
  },
  {
    "id": 174,
    "domain": "D3",
    "body": "Route 53のヘルスチェックとフェイルオーバーの目的はどれか。",
    "choice_a": "Lambdaのメモリを増やす",
    "choice_b": "S3をIAにする",
    "choice_c": "死んだエンドポイントから生きている方へ名前解決を切り替える",
    "choice_d": "EBSを暗号化する",
    "correct": "C",
    "explain": "DNSレベルでの切り替え。"
  },
  {
    "id": 175,
    "domain": "D3",
    "body": "VPCエンドポイント（Gateway型）でよくS3へ行く理由はどれか。",
    "choice_a": "S3の料金が必ず無料になる",
    "choice_b": "EBSが不要になる",
    "choice_c": "Rootが不要になる",
    "choice_d": "インターネットを経由せずVPC内からS3へ行ける",
    "correct": "D",
    "explain": "プライベート接続。"
  },
  {
    "id": 176,
    "domain": "D3",
    "body": "AMIの説明として適切なものはどれか。",
    "choice_a": "EC2を起動するためのマシンイメージ",
    "choice_b": "S3のストレージクラス",
    "choice_c": "WAFのルール",
    "choice_d": "請求のタグ",
    "correct": "A",
    "explain": "OS入りのテンプレート。"
  },
  {
    "id": 177,
    "domain": "D4",
    "body": "短期間・予測できないEC2の買い方はどれか。",
    "choice_a": "Dedicated Hostだけ",
    "choice_b": "On-Demand",
    "choice_c": "3年のReservedだけ",
    "choice_d": "Spotだけ",
    "correct": "B",
    "explain": "単価は高め。"
  },
  {
    "id": 178,
    "domain": "D4",
    "body": "1年または3年使うと分かっているときの買い方はどれか。",
    "choice_a": "毎回最大オンデマンド",
    "choice_b": "データ送信無料プラン",
    "choice_c": "Reserved Instance または Savings Plans",
    "choice_d": "Spotのみ",
    "correct": "C",
    "explain": "長期割引。"
  },
  {
    "id": 179,
    "domain": "D4",
    "body": "中断されてもよいバッチに向く買い方はどれか。",
    "choice_a": "Dedicated Host",
    "choice_b": "Reservedの全前払いだけ",
    "choice_c": "Enterpriseサポート",
    "choice_d": "Spot Instance",
    "correct": "D",
    "explain": "余っている容量。取り上げられる。"
  },
  {
    "id": 180,
    "domain": "D4",
    "body": "既存ライセンスで物理占有が必要なときに使うのはどれか。",
    "choice_a": "Dedicated Host",
    "choice_b": "Spot",
    "choice_c": "S3 Standard",
    "choice_d": "CloudFront",
    "correct": "A",
    "explain": "ソケット/コアが見える。"
  },
  {
    "id": 181,
    "domain": "D4",
    "body": "これから使う分の見積もりツールはどれか。",
    "choice_a": "Amazon Inspector",
    "choice_b": "AWS Pricing Calculator",
    "choice_c": "AWS Cost Explorer",
    "choice_d": "Amazon GuardDuty",
    "correct": "B",
    "explain": "将来の試算。過去はExplorer。"
  },
  {
    "id": 182,
    "domain": "D4",
    "body": "過去の利用料をグラフで分析するのはどれか。",
    "choice_a": "Amazon Rekognition",
    "choice_b": "Amazon Polly",
    "choice_c": "AWS Cost Explorer",
    "choice_d": "AWS Pricing Calculator",
    "correct": "C",
    "explain": "何にいくら使ったか。"
  },
  {
    "id": 183,
    "domain": "D4",
    "body": "予算超過を通知するのはどれか。",
    "choice_a": "Amazon SNSだけ（単体では予算を定義しない）",
    "choice_b": "AWS WAF",
    "choice_c": "Amazon EFS",
    "choice_d": "AWS Budgets",
    "correct": "D",
    "explain": "しきい値とアラート。SNSは通知先。"
  },
  {
    "id": 184,
    "domain": "D4",
    "body": "最も詳細な請求データはどれか。",
    "choice_a": "AWS Cost and Usage Report",
    "choice_b": "Trusted Advisorの無料項目だけ",
    "choice_c": "CloudFrontの価格クラス名",
    "choice_d": "AMI名",
    "correct": "A",
    "explain": "CUR。"
  },
  {
    "id": 185,
    "domain": "D4",
    "body": "複数アカウントの請求をまとめるのはどれか。",
    "choice_a": "Amazon Lex",
    "choice_b": "AWS Organizations の一括請求",
    "choice_c": "Amazon S3 Glacier",
    "choice_d": "AWS Shield Standard",
    "correct": "B",
    "explain": "Consolidated billing。"
  },
  {
    "id": 186,
    "domain": "D4",
    "body": "データ転送で原則無料になりやすいものはどれか。",
    "choice_a": "リージョン間転送",
    "choice_b": "AZをまたぐデータ転送",
    "choice_c": "インターネットからの受信（ingress）",
    "choice_d": "インターネットへの送信（egress）",
    "correct": "C",
    "explain": "出る方が課金されやすい。例外はある。"
  },
  {
    "id": 187,
    "domain": "D4",
    "body": "Basicサポートの説明として正しいものはどれか。",
    "choice_a": "TAMが必ず付く",
    "choice_b": "24時間電話が標準",
    "choice_c": "本番障害で15分応答が保証される",
    "choice_d": "無料。Trusted Advisorは一部のみ",
    "correct": "D",
    "explain": "有償プランで範囲が広がる。"
  },
  {
    "id": 188,
    "domain": "D4",
    "body": "本番ワークロード向けでTrusted Advisorが全項目使えるプランはどれか。",
    "choice_a": "Business 以上",
    "choice_b": "Basicだけ",
    "choice_c": "Developerだけ",
    "choice_d": "無料利用枠",
    "correct": "A",
    "explain": "Business / Enterprise系。"
  },
  {
    "id": 189,
    "domain": "D4",
    "body": "テクニカルアカウントマネージャー（TAM）が付くのはどれか。",
    "choice_a": "無料のフォーラムだけ",
    "choice_b": "Enterprise または Enterprise On-Ramp",
    "choice_c": "Basic",
    "choice_d": "Developer",
    "correct": "B",
    "explain": "大規模向け。"
  },
  {
    "id": 190,
    "domain": "D4",
    "body": "Developerサポートの位置づけはどれか。",
    "choice_a": "DDoS補償",
    "choice_b": "S3の11ナイン保証の別名",
    "choice_c": "開発・検証向け。営業時間の案内",
    "choice_d": "全企業の本番SLA",
    "correct": "C",
    "explain": "本番はBusiness以上。"
  },
  {
    "id": 191,
    "domain": "D4",
    "body": "Trusted Advisorの5カテゴリに含まれるものはどれか。",
    "choice_a": "人事評価",
    "choice_b": "ロゴデザイン",
    "choice_c": "オフィスの賃料",
    "choice_d": "サービス制限（クォータ）",
    "correct": "D",
    "explain": "コスト・性能・セキュリティ・耐障害性・制限。"
  },
  {
    "id": 192,
    "domain": "D4",
    "body": "コスト配分タグの用途はどれか。",
    "choice_a": "部門やプロジェクトごとに費用を分ける",
    "choice_b": "EC2のCPUを上げる",
    "choice_c": "S3を暗号化する",
    "choice_d": "WAFを無効にする",
    "correct": "A",
    "explain": "誰の請求か見える化。"
  },
  {
    "id": 193,
    "domain": "D4",
    "body": "Savings Plansの説明として適切なものはどれか。",
    "choice_a": "DNS",
    "choice_b": "一定の利用を約束して割引を受ける",
    "choice_c": "DDoS対策サービス",
    "choice_d": "コンテナオーケストレーション",
    "correct": "B",
    "explain": "RIより柔軟な約束割引。"
  },
  {
    "id": 194,
    "domain": "D4",
    "body": "請求に関する質問を公式に確認する場所として適切なものはどれか。",
    "choice_a": "S3バケット名",
    "choice_b": "AMIの説明文だけ",
    "choice_c": "AWS Billing / Support Center と公式ドキュメント",
    "choice_d": "任意の掲示板の噂だけ",
    "correct": "C",
    "explain": "Billingコンソール。"
  },
  {
    "id": 195,
    "domain": "D4",
    "body": "無料利用枠を超えたときに起きやすいことはどれか。",
    "choice_a": "アカウントが必ず削除される",
    "choice_b": "データが消える",
    "choice_c": "IAMが無効になる",
    "choice_d": "従量課金が発生する",
    "correct": "D",
    "explain": "Budgetsで先に知らせる。"
  },
  {
    "id": 196,
    "domain": "D4",
    "body": "同じAZ内のプライベートIP通信の課金イメージとして近いものはどれか。",
    "choice_a": "リージョン間やインターネット出口より安くなりやすい",
    "choice_b": "必ず国際回線と同じ単価",
    "choice_c": "常にDeep Archiveより高い",
    "choice_d": "サポートプランで決まる",
    "correct": "A",
    "explain": "詳細はサービスによるが「出口と跨ぎ」が高い。"
  },
  {
    "id": 197,
    "domain": "D4",
    "body": "AWS Marketplaceの請求の特徴として適切なものはどれか。",
    "choice_a": "TAMが商品である",
    "choice_b": "サードパーティ製品代がAWSの請求に乗る場合がある",
    "choice_c": "必ず別の銀行振込だけ",
    "choice_d": "S3のGlacierと相殺される",
    "correct": "B",
    "explain": "一枚の請求にまとまることがある。"
  },
  {
    "id": 198,
    "domain": "D4",
    "body": "ヘルスダッシュボード（AWS Health）の用途はどれか。",
    "choice_a": "Lambdaを書く",
    "choice_b": "WAFの正規表現を作る",
    "choice_c": "自分のアカウントに影響する障害・メンテを見る",
    "choice_d": "S3のクラスを変える",
    "correct": "C",
    "explain": "Service HealthとAccount Health。"
  },
  {
    "id": 199,
    "domain": "D4",
    "body": "サポートケースを切る場所はどれか。",
    "choice_a": "Amazon S3コンソールのライフサイクルだけ",
    "choice_b": "Route 53のTTL",
    "choice_c": "EC2のスポット履歴だけ",
    "choice_d": "AWS Support Center",
    "correct": "D",
    "explain": "プランにより電話やチャットも。"
  },
  {
    "id": 200,
    "domain": "D4",
    "body": "コスト最適化で最初にやることに近いものはどれか。",
    "choice_a": "Cost Explorerで内訳を見て、未使用を止める",
    "choice_b": "全リソースを最大サイズにする",
    "choice_c": "CloudTrailを止める",
    "choice_d": "パブリックS3にする",
    "correct": "A",
    "explain": "見える化が先。"
  }
];
